POST http://127.0.0.1:8000/auth/users/
Content-Type: application/json

{
    "username": "Tanya",
    "password": "aicotoba32"
}
###
POST http://127.0.0.1:8000/auth/jwt/verify/
Authorization:  Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI5NjMyNjU5LCJqdGkiOiIzZjliYmZkODQzMjg0YmYxYWJkZTM5NWU1NjRhOWEyMiIsInVzZXJfaWQiOjF9.tsk1w8Wsv6jqXV1FbM29vdVXOAC5TtpNAPfWv4TwsBg
Content-Type: application/json

{
   "token": "string"
}
###
POST http://127.0.0.1:8000/api/v1/posts/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI5NTQ2MTc3LCJqdGkiOiJmMDdhYmYxOWM5Y2E0OTg3OTg3NDMxYWI1YzlhNmI0YSIsInVzZXJfaWQiOjF9.viky2GHh3iE_Mc8qv51fRDQ9cuo3983X58J0GFwYcIU
Content-Type: application/json

{
    "text": "text",
    "group": null
}
###
GET http://127.0.0.1:8000/api/v1/follow/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI5NjMyNjU5LCJqdGkiOiIzZjliYmZkODQzMjg0YmYxYWJkZTM5NWU1NjRhOWEyMiIsInVzZXJfaWQiOjF9.tsk1w8Wsv6jqXV1FbM29vdVXOAC5TtpNAPfWv4TwsBg
###
GET http://127.0.0.1:8000/api/v1/follow/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI5NjMyNjU5LCJqdGkiOiIzZjliYmZkODQzMjg0YmYxYWJkZTM5NWU1NjRhOWEyMiIsInVzZXJfaWQiOjF9.tsk1w8Wsv6jqXV1FbM29vdVXOAC5TtpNAPfWv4TwsBg
###
POST http://127.0.0.1:8000/api/v1/follow/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI5NjMyNjU5LCJqdGkiOiIzZjliYmZkODQzMjg0YmYxYWJkZTM5NWU1NjRhOWEyMiIsInVzZXJfaWQiOjF9.tsk1w8Wsv6jqXV1FbM29vdVXOAC5TtpNAPfWv4TwsBg
Content-Type: application/json

{
    "user": "Roman",
    "following": "Tonya"
}
###
GET http://127.0.0.1:8000/api/v1/groups/
###
