# Generated by Django 3.2.6 on 2021-08-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('posts', '0002_follow_unique_user_following')]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow', name='unique_user_following'
        )
    ]
